package classesobjetos.aula16.livros

fun main() {
    val livroFavorito = Livros("O Pequeno Príncipe", 98, 20)
    println("${livroFavorito.titulo} possui ${livroFavorito.qtdPaginas} páginas.")
    print("\n")
    val livro1 = Livros("Vigiar e Punir", 320, 30)
    println("${livro1.titulo} possui ${livro1.qtdPaginas} páginas.")
    livro1.verificarProgresso()
    print("\n")
    val livro2 = Livros("Sapiens",400,30)
    println("${livro2.titulo} possui ${livro2.qtdPaginas} páginas.")
    livro2.verificarProgresso()
    print("\n")
    val livro3 = Livros("Admirável Mundo Novo",300,300)
    println("${livro3.titulo} possui ${livro3.qtdPaginas} páginas.")
    livro3.verificarProgresso()
    print("\n")
    val livro4 = Livros("Guerra e Paz",1000,400)
    println("${livro4.titulo} possui ${livro4.qtdPaginas} páginas.")
    livro4.verificarProgresso()
    print("\n")
    val livro5 = Livros("O idiota",203,20)
    println("${livro5.titulo} possui ${livro5.qtdPaginas} páginas.")
    livro5.verificarProgresso()
    print("\n")
    val livro6 = Livros("A ilha", 280, 50)
    println("${livro6.titulo} possui ${livro6.qtdPaginas} páginas.")
    livro6.verificarProgresso()
    print("\n")
    val livro7 = Livros( "Terrorismo",380,20)
    println("${livro7.titulo} possui ${livro7.qtdPaginas} páginas.")
    livro7.verificarProgresso()
    print("\n")
    val livro8 = Livros("Introdução a lógica",170,40)
    println("${livro8.titulo} possui ${livro8.qtdPaginas} páginas.")
    livro8.verificarProgresso()
    print("\n")
    val livro9 = Livros("Além do bem e do mal",349,20)
    println("${livro9.titulo} possui ${livro9.qtdPaginas} páginas.")
    livro9.verificarProgresso()
    print("\n")
    val livro10 = Livros("Ecce homo",200,70)
    println("${livro10.titulo} possui ${livro10.qtdPaginas} páginas.")
    livro10.verificarProgresso()
}
